---
title: "Project Penilaian Service"
output: html_document
date: "2023-04-17"
---

```{r}
library("readxl")
```


```{r}
data=read_excel("E:\\disertasi\\DISERTASI JURNAL\\SUBMIT P2\\PENELITIAN JURNAL 1\\DATA UJI TGL 19 AGUSTUS 2023_REV.xlsx")
```


```{r}
# Data di read menggunakan library read excel dikarenakan adanya dataset berupa data excel dengan menggunakan syntax read_excel.
```



```{r}
data
```
```{r}
#install.packages('psych')
library(psych)
describe(data)
```
```{r}
multi.hist(data)
```
```{r}
library(ggcorrplot)
ggcorrplot(cor(data),hc.order = TRUE,
           type = "lower",
           lab = TRUE)
```

```{r}
boxplot(data)
```

```{r}

# model yang digunakan merupakan model structural equation model. Structured equation model merupakan model yang membantu untuk menjelaskan hubungan antara variabel terukur dengan variabel latent dan hubungan antara variabel laten. laten variabel merupaakn variabel meruapakn variabel yang secara konsep manusia mampu mengerti namun tidak dapat diukur secara langsung. Pada diatas dapat diketahui bahwa penilaian kepercayaan merupakan salah satu latent variabel yang tidak dapat diukur secara langsung namun dapat diukur dengan service characteristic, basic service, personlized service dan social attribut. Beberapa independen laten variabel diantaranya adalah quality service dan perceived reputation. beberapa arah panah menunjukan 2 latent variabel diatas diharapkan mampu memberikan efek pada e trust. kesembilan pengukuran variabel yang berada bagian kiri diharapkan memberikan dampak pada setiap independent variabelnya . Tujuan dari teknik SEM ini adalah untuk mengestimasi koefisien pada setiap panah. 

```
```{r}
data
```


```{r}
#install.packages('lavaan')
library('lavaan')
model=' E_CyberThreatIntelligence=~ECT.01+ECT.02+ECT.03
E_CustomerExperience=~ECX.01+ECX.02+ECX.03
E_ServiceQuality=~ESQ.01+ESQ.02
E_Trust=~ET.01+ET.02+ET.03
E_Satisfaction=~ES.01+ES.02
E_Trust~E_CyberThreatIntelligence+E_CustomerExperience+E_ServiceQuality
E_Satisfaction~E_Trust
E_Satisfaction~E_ServiceQuality+E_CyberThreatIntelligence'
```




```{r}
# model perlu didefinisikan sebelum dilakukan fiting untuk memetakan setiap hubungan yang muncul pada setiap variabel latent dan measured. Penggunaan simbol =~ digunakan untuk memberikan definisi hubungan antara latent variabel dan measured. Lalu penggunaan ~ digunakan untuk membangun model regresi antara satu latent variabel dengan lainnya. 
```
```{r}
fit=sem(model,data=data)
summary(fit,standardized=TRUE)
```
```{r}
fitmeasures(fit)
```

```{r}
library(semPlot)
semPaths(fit, "std", rotation=2, layout = "tree2", curvature = 2, nCharNodes = 0, nDigits = 3,
             sizeMan = 10, sizeInt = 15, sizeLat = 10, edge.label.cex=1.2, exoVar = FALSE, fade=FALSE)
```
```{r}
## Chi Squared Test
# Pada chi square test didapatkan nilai p value yang menilai seberapa penting model mampu menjelaskan beberapa bagian variasi pada data. Nilai pvalue pada data perlu dibawah 0.05 untuk menjadi signifikan dan pada kasus ini nilai tersebut sudah terpenuhi pada model diatas.
## Regression Coefficient pada Structured Equation Model
# Pertama tama yang perlu diperhatikan adlaah pvalue pada independent latent variabel.Jika setiap p value memiliki nilai dibawah 0,05 maka spedific latent variabel memengaruhi dependent latent variabel. Pada kasus ini setiap independen latent variabel memiliki nilai dibawah 0.05 sehingga setiap independen latent memiliki pengaruh pada kinerja e_trust.
# Selanjutnya untuk mengetahui independent latent variabel yang paling berpengaruh pada e trust dapat menggunakan koefisien yang muncul independent latent pada regresi model. Dapat terlihat bahwa quality service merupakan variabel paling berpengaruh dibandingkan dengan perceived reputation ditunjukan dengan nilai estimasi koefisien 0.865 pada quality service dan 0.162 pada perceived reputation.

```

```{r}
fitmeasures(fit)
```

```{r}
install.packages('semPlot')

```

```{r}
library(semPlot)
semPaths(fit, "std", rotation=2, layout = "tree2", curvature = 2, nCharNodes = 0, nDigits = 3,
             sizeMan = 10, sizeInt = 15, sizeLat = 10, edge.label.cex=1.2, exoVar = FALSE, fade=FALSE)
```

```{r}
data_gambar=data.frame(estimate_coefficient=c(0.322,0.280,0.309),latent_independent_variabel=c('E_CyberThreatIntelligence','E_CustomerExperience','E_ServiceQuality'))
library(ggplot2)
p=ggplot(data=data_gambar,aes(x=latent_independent_variabel,y=estimate_coefficient))+geom_bar(stat='identity',fill='steelblue')+geom_text(aes(label=estimate_coefficient), vjust=1.6, color="white", size=3.5)
p+labs(title='E_CyberThreatIntelligence+E_CustomerExperience+E_ServiceQuality to E-Trust')

```

```{r}
data_gambar=data.frame(estimate_coefficient=c(-0.074,0.280,0.480),latent_independent_variabel=c('E_ServiceQuality','E_CyberThreatIntelligence','E-Trust'))
library(ggplot2)
p=ggplot(data=data_gambar,aes(x=latent_independent_variabel,y=estimate_coefficient))+geom_bar(stat='identity',fill='steelblue')+geom_text(aes(label=estimate_coefficient), vjust=1.6, color="white", size=3.5)
p+labs(title='E_ServiceQuality+E_CyberThreatIntelligence+E-Trust to E-Satisfaction')

```
